export enum EParteiName {
  CSU = "CSU",
  SPD = "SPD",
  FREIE_WAEHLER = "Freie Wähler",
  GRUENE = "Grüne",
  FDP = "FDP",
  DIE_LINKE = "Die Linke",
  BAYERN_PARTEI = "Bayern Partei",
  OEDP = "ÖDP",
  PIRATEN = "Piraten",
  DIE_FRANKEN = "Die Franken",
  AFD = "AfD",
  LKR = "LKR",
  MUT = "mut",
  DIE_HUMANISTEN = "Die Humanisten",
  DIE_PARTEI = "Die Partei",
  GESUNDHEITSFORSCHUNG = "Gesundheitsforschung",
  TIERSCHUTZPARTEI = "Tierschutzpartei",
  V_PARTEI = "V-Partei"
}
