build-specification-pdfs:
  script: 
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -y
  - apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-metapost texlive-lang-german texlive-latex-extra nodejs build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
  - npm install canvas 
  - npm install -g mdgen
  - cd specification/
  - mdgen pdf -m model.mdj -o model.pdf
  - cd Lastenheft
  - make
  artifacts:
    paths:
    - specification/Lastenheft/Lastenheft.pdf
    - specification/model.pdf
