build-lastenheft:
  script: "uname -a; apt-get update -y && apt-get install -y texlive texlive-full && cd specification/Lastenheft && make"
  artifacts:
    paths:
    - specification/Lastenheft/Lastenheft.pdf
