build-lastenheft:
  script: "uname -a; apt-get update -y && apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-metapost texlive-lang-german && tlmgr install glossaries && cd specification/Lastenheft && make"
  artifacts:
    paths:
    - specification/Lastenheft/Lastenheft.pdf
